### ISSUE TITLE
Вопрос. Обработка нажатий.

### ISSUE THREAD

**Issue by Nivanchenko** [ahyahy/OneScriptForms#4]
Здравствуйте!
Пытаюсь запустить код из примера в документации
```bsl
Перем Ф;

Процедура Форма1_КлавишаВверх_КлавишаВниз()
	КлавишаАрг1 = Ф.КлавишаАрг();
	Сообщить("КлавишаАрг1.Alt = " + КлавишаАрг1.Alt);
	Сообщить("КлавишаАрг1.Ctrl = " + КлавишаАрг1.Ctrl);
	Сообщить("КлавишаАрг1.Shift = " + КлавишаАрг1.Shift);
	Сообщить("КлавишаАрг1.КодКлавиши = " + КлавишаАрг1.КодКлавиши);
	Сообщить("КлавишаАрг1.Модификаторы = " + КлавишаАрг1.Модификаторы);
	Сообщить("===========================================");
КонецПроцедуры

ПодключитьВнешнююКомпоненту("C:\Users\n.ivanchenko\Documents\APPS\OneGame\src\Классы\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Ширина = 600;
Форма1.Высота = 400;
Форма1.Текст = "Нажмите Alt или Ctrl или Shift";
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();

Форма1.КлавишаВниз = "Форма1_КлавишаВверх_КлавишаВниз()";
Форма1.КлавишаВверх = "Форма1_КлавишаВверх_КлавишаВниз()";
	
Пока Ф.Продолжать Цикл
	Выполнить(Ф.ПолучитьСобытие());
КонецЦикла;
```
Но на любые нажатия получаю вывод
```
КлавишаАрг1.Alt = Нет
КлавишаАрг1.Ctrl = Нет
КлавишаАрг1.Shift = Нет
КлавишаАрг1.КодКлавиши = 0
КлавишаАрг1.Модификаторы = 0
===========================================
```
Дотнет не является моей сильной стороной. Если я полезу туда, погрязну на долго. Может есть какой-то нюанс, который я упускаю. Основная идея, я запускаю форму, и хочу отлавливать все нажатия с клавиатуры.

**Comment by ahyahy** [comment]
Re: [ahyahy/OneScriptForms] Вопрос. Обработка нажатий. (#4)
Спасибо за найденную ошибку! Вот досада, проверял основательно, но объем большой, упустил.
Надо бы пересмотреть тестовые коды.
Дело вот в чем:
В файле Control.cs есть обработка события для КлавишаВверх, КлавишаВниз.
В ней создается событие, ставится в очередь событий, но вот аргументы события переменным не присваивались.
Нужно добавить эти несколько строчек. Должно получиться следующее:

        private void m_Control_KeyDown(object sender, System.Windows.Forms.KeyEventArgs e)
        {
            if (KeyDown.Length > 0)
            {
                KeyEventArgs KeyEventArgs1 = new KeyEventArgs();
                KeyEventArgs1.EventString = KeyDown;
                KeyEventArgs1.Sender = this;

                KeyEventArgs1.Alt = e.Alt;
                KeyEventArgs1.Control = e.Control;
                KeyEventArgs1.KeyCode = (int)e.KeyCode;
                KeyEventArgs1.Modifiers = (int)e.Modifiers;
                KeyEventArgs1.Shift = e.Shift;

                OneScriptForms.EventQueue.Add(KeyEventArgs1);
                ClKeyEventArgs ClKeyEventArgs1 = new ClKeyEventArgs(KeyEventArgs1);
            }
        }

        private void m_Control_KeyUp(object sender, System.Windows.Forms.KeyEventArgs e)
        {
            if (KeyUp.Length > 0)
            {
                KeyEventArgs KeyEventArgs1 = new KeyEventArgs();
                KeyEventArgs1.EventString = KeyUp;
                KeyEventArgs1.Sender = this;

                KeyEventArgs1.Alt = e.Alt;
                KeyEventArgs1.Control = e.Control;
                KeyEventArgs1.KeyCode = (int)e.KeyCode;
                KeyEventArgs1.Modifiers = (int)e.Modifiers;
                KeyEventArgs1.Shift = e.Shift;

                OneScriptForms.EventQueue.Add(KeyEventArgs1);
                ClKeyEventArgs ClKeyEventArgs1 = new ClKeyEventArgs(KeyEventArgs1);
            }
        }

Пожалуйста замените эти обработчики в файле Control.cs
Я в новом релизе это сделаю, он выйдет недели через две (я надеюсь уложиться).
Хочу ещё раз перепроверить. Добавил несколько методов и свойств, позволяющих не замирать 
приложение при длительных вычислениях, ну и кое что ещё.
Кстати хочу одновременно с новым релизом форм опубликовать дизайнер форм к моим формам.
Всё на русском...
Да, ещё. ЭлементУправления.КлавишаНажата (Control.KeyPress) Свойство тоже может Вам пригодиться.

**Comment by Nivanchenko** [comment]
Control.KeyPress, на сколько я понял, оно возвращает нажатый символ. Это тоже полезно, но там много нюансов появляется с раскладкой клавиатуры. За пример спасибо, попробую. Про дизайнер форм новость огонь.

**Comment by Nivanchenko** [comment]
Спасибо. Мне удалось исправить и собрать. Работает.
