### ISSUE TITLE
Предложение. Обработчики событий форм и элементов

### ISSUE THREAD

**Issue by Nivanchenko** [ahyahy/OneScriptForms#5]
Добрый день, пользуясь библиотекой, я для себя выдумал определенную методику обработки событий.

Вместо
```bsl
Процедура НажатиеКнопки()
	Сумма = 2+1;
	Сообщить("Событие, и результат " + Строка(Сумма));
КонецПроцедуры

ПодключитьВнешнююКомпоненту("C:\Users\n.ivanchenko\Documents\APPS\OneGame\src\Классы\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Текст = "Форма1";
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();

Кнопка1 = Форма1.ЭлементыУправления.Добавить(Ф.Кнопка());
Кнопка1.Границы = Ф.Прямоугольник(10, 10, 75, 25);
Кнопка1.Текст = "Кнопка1";
Кнопка1.Нажатие = "НажатиеКнопки()";

Пока Ф.Продолжать Цикл
	Выполнить(Ф.ПолучитьСобытие());
КонецЦикла;
```
Я создаю контейнер - соответствие имен событий и делегатов(действий). И при обработке очереди событий выполняю их.
Упрощенный пример:
```bsl
Перем СобытияФормы;

Процедура НажатиеКнопки(Доппараметр = 0) Экспорт
	Сумма = Доппараметр * 2;
	Сообщить("Событие, и результат " + Строка(Сумма));
КонецПроцедуры

СобытияФормы = Новый Соответствие();

ПодключитьВнешнююКомпоненту("C:\Users\n.ivanchenko\Documents\APPS\OneGame\src\Классы\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Текст = "Форма1";
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();

Кнопка1 = Форма1.ЭлементыУправления.Добавить(Ф.Кнопка());
Кнопка1.Границы = Ф.Прямоугольник(10, 10, 75, 25);
Кнопка1.Текст = "Кнопка1";
Кнопка1.Нажатие = "НажатиеКнопки";

СобытияФормы.Вставить("НажатиеКнопки", Новый Действие(ЭтотОбъект, "НажатиеКнопки"));

Пока Ф.Продолжать Цикл
	Событие = Ф.ПолучитьСобытие();

	Если не СобытияФормы[Событие] = Неопределено Тогда
		СобытияФормы[Событие].Выполнить(5);
	КонецЕсли;

КонецЦикла;
```

Чем мне такой подход нравится больше
 - В vscode таким образом стабильно работает отладка внутри обработчиков событий
 - В такой метод удобно пробросить дополнительные параметры, если того требует логика приложения
 - Уход от "Выполнить()"
 
И узнав, что Вы готовите новый релиз, у меня вопрос\предложение (я не знаю, а вдруг это достаточно просто реализуется) - добавить возможность в методы форм присваивать значения не только с типом строка, но и типом Действие. 
```bsl
Кнопка1.Нажатие = Новый Действие(ЭтотОбъект, "НажатиеКнопки");
```

Тогда получив событие, из очереди его можно выполнить.
Полный пример
```bsl
Процедура НажатиеКнопки() Экспорт
	Сумма = 2+1;
	Сообщить("Событие, и результат " + Строка(Сумма));
КонецПроцедуры

ПодключитьВнешнююКомпоненту("C:\Users\n.ivanchenko\Documents\APPS\OneGame\src\Классы\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Текст = "Форма1";
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();

Кнопка1 = Форма1.ЭлементыУправления.Добавить(Ф.Кнопка());
Кнопка1.Границы = Ф.Прямоугольник(10, 10, 75, 25);
Кнопка1.Текст = "Кнопка1";
Кнопка1.Нажатие = Новый Действие(ЭтотОбъект, "НажатиеКнопки");

Пока Ф.Продолжать Цикл
	Событие = Ф.ПолучитьСобытие();

	Если ТипЗнч(Событие) = Тип("Действие") Тогда
		Событие.Выполнить();
	КонецЕсли;

КонецЦикла;
```

**Comment by ahyahy** [comment]
Здравствуйте, Nikita.
Так на вскидку - это реализовать можно.
Сейчас порассуждаю немного.
Где то я там уже передавал из скрипта в код c# массив. Другие типы тоже можно пропихнуть через параметр типа IValue. Меняем string на IValue и почти готово.
Вспоминается принцип бритвы Оккама - Не следует привлекать новые сущности без крайней на то необходимости .
У нас ведь есть процедура нажатия кнопки записанная в скрипте. Там можно много чего прописать.
Но хороший агрумент нужности - работа в vscode. Вот только я до него ещё не добрался. Каюсь, всё ещё в Notepad++.
Функциональность несомненно расширится.
Боюсь выйти из плана. Я тут недавно опять над своим архиватором завис на два дня, а ведь надо дизайнер доделать и новый релиз форм, исправленный и дополненный выпустить.
Ну вот ещё мысль. Можно ведь из скрипта создавать события напрямую, и помещать в очередь событий. То есть дать возможность кодеру создавать свои события, а не использовать генерируемые формой и элементами.
Это даже проще будет. Дать возможность создать в скрипте объект - ОчередьСобытий и в разумных пределах управлять ей. Надо подумать.

**Comment by Nivanchenko** [comment]
На самом деле. Пример 2, выше с использованием соответствия, уже сейчас работает, и позволяет останавливаться в отладке в методах элементов. Мы к нему пришли, в тот момент, когда в нашем приложении появилось несколько форм, и мы захотели разделить по разным файлам/классам код каждой формы. И через выполнить() в какой-то момент это стало выглядеть не очень красиво. И с увеличением сложности, понадобилась живая отладка.

**Comment by ahyahy** [comment]
Так, интересно.
Это только первый релиз. Необходимый минимум. И в процессе применения будет проясняться куда нужно двигаться.
Хорошо если бы Вы обрисовали взаимодействие форм чуть подробнее. Задумка мне кажется реализуемой, но может я увиже ещё какие то пути, исходя из материала.

**Comment by Nivanchenko** [comment]
Хорошо. Мне нужно некоторое время, что бы подготовить чистый и понятный пример.

**Comment by ahyahy** [comment]
Здравствуйте, Nikita.
Поэкспериментировал с нынешним релизом и нашел два интересных варианта, не требующих изменения библиотеки.
А так же реализовал Ваше предложение, изменив библиотеку, тоже два варианта предложу на рассмотрение. Нужно обсудить и остановиться на лучшем решении. Измененную, экспериментальную библиотеку присоединяю к письму, не знаю пролезет на гит или нет. Она (experiment.dll) для наглядности скорее всего, там только свойство Форма1.Нажатие сработает, остальные события не трогал.
Итак.

//вариант1===============================
Процедура НажатиеФормы(Доппараметр = 0) Экспорт
        Сообщить("Результат = " + (Доппараметр / 1000));
КонецПроцедуры

ПодключитьВнешнююКомпоненту("C:\444\111\OneScriptForms\OneScriptForms\bin\Debug\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();
Форма1.Нажатие = "НажатиеФормы()";

Пока Ф.Продолжать Цикл
        Выполнить(СтрЗаменить(Ф.ПолучитьСобытие(), "()", "(" + ТекущаяУниверсальнаяДатаВМиллисекундах() + ")"));
КонецЦикла;
// релиз текущий, немного изменил содержание цикла. Параметр можно передать таким образом, без использования типа "Действие"
// нет ухода от Выполнить, и наверное в отладчике будут недоступны методы формы.


//вариант2===============================
Процедура НажатиеФормы(Доппараметр = 0) Экспорт
        Сообщить("Результат = " + (Доппараметр / 1000));
КонецПроцедуры

ПодключитьВнешнююКомпоненту("C:\444\111\OneScriptForms\OneScriptForms\bin\Debug\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();
Форма1.Нажатие = "НажатиеФормы()";

Пока Ф.Продолжать Цикл
        Действие = Новый Действие(ЭтотОбъект, СтрЗаменить(Ф.ПолучитьСобытие(), "()", ""));
        Действие.Выполнить(ТекущаяУниверсальнаяДатаВМиллисекундах());
КонецЦикла;
// релиз текущий, немного изменил содержание цикла. Параметр передается, используется тип "Действие"
// свойство Форма1.Нажатие осталось строковым.


Варианты доработанной библиотеки.
//планируемый - вариант3===============================
Перем Ф;

Процедура НажатиеФормы() Экспорт
        Сообщить("Ф.АргументыСобытия.Параметр = " + Ф.АргументыСобытия.Параметр);
КонецПроцедуры

ПодключитьВнешнююКомпоненту("C:\444\111\OneScriptForms\OneScriptForms\bin\Debug\experiment.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();

Пока Ф.Продолжать Цикл
        Форма1.Нажатие = Ф.СловарнаяЗапись("" + (Новый Массив()).Количество() + " ; " + ТекущаяУниверсальнаяДатаВМиллисекундах(), "НажатиеФормы()");
        Событие = Ф.ПолучитьСобытие();
        Попытка
                Выполнить(Событие);
        Исключение
        КонецПопытки;
КонецЦикла;
// здесь попытка используется для устранения ошибки при закрытии формы
// просто недоработка из за нехватки времени, устраню в дальнейшем 
// ключ словарной записи как объект передается в атрибут события и доступен в обработчике как Ф.АргументыСобытия.Параметр
// Свойство Форма1.Нажатие нужно будет переопределять, если нужно получить меняющиеся данные.
// если нужно передать объект один и тот же, можно вынести это свойство из цикла.


//планируемый - вариант4===============================
Перем Ф;

Процедура НажатиеФормы(Доппараметр = 0) Экспорт
        Сообщить("Результат = " + (Доппараметр / 1000));
        Сообщить("Ф.АргументыСобытия.Параметр = " + Ф.АргументыСобытия.Параметр);
КонецПроцедуры

ПодключитьВнешнююКомпоненту("C:\444\111\OneScriptForms\OneScriptForms\bin\Debug\experiment.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();
Форма1.Нажатие = Новый Действие(ЭтотОбъект, "НажатиеФормы");

Пока Ф.Продолжать Цикл
        Событие = Ф.ПолучитьСобытие();
        Попытка
                Событие.Выполнить(ТекущаяУниверсальнаяДатаВМиллисекундах());
        Исключение
                Выполнить(Событие);
        КонецПопытки;
КонецЦикла;
// здесь попытка используется для совместимости с прежним типом значения (Строка) свойства Форма1.Нажатие
// кстати, в новом релизе скобки у свойства будут не обязательны
// Ф.АргументыСобытия.Параметр в этом случае - это экземпляр типа "Действие"

Что вы об этом думаете?
Мне так и не понятна передача парамерта в обработчик события. Му ведь и так в скрипте находимся, весь контекст доступен.
Вы говорите о нескольких формах. Можно ведь создавать подчиненные формы. Самая первая - форма вехнего уровня. Если поясните - хорошо.

**Comment by Nivanchenko** [comment]
Добрый день, в почту не пролезла длл. Можете мне на почту прислать ? n1k17ka@gmail.com. Я тогда попробую сегодня

**Comment by Nivanchenko** [comment]
https://github.com/Nivanchenko/test-example-onescript-forms
Посмотрите пожалуйста, я собрал пример, того как удалось сейчас реализовать. Суть в том что в события можно записывать только текстовые значения, я через все формы таскаю соответствие, где ключ - имя метода, значение - объект действие. И уже получается довольно удобно. Но приходится уникальный имена методов, что бы они не перезаписали друг друга. 
Это почти как у Вас 4 вариант (который как по мне очень крут), только с костылем в виде соответствия имени метода и действия.  Но кажется это огромный труд ко всем методам, всех элементов сделать второй тип события - Действие.
Мне не понятно что такое
Ф.АргументыСобытия.Параметр, в  4 варианте мы его никак не определяем, оно как-то под капотом формируется? и что туда созраняется?

**Comment by Nivanchenko** [comment]
Мне кажется я Вас уже замучил, но у меня еще возникла идея.
В 1Ске каждый элементы формы биндится к данным, т.е. у элемента есть реквизит Данные = "Объект.Наименование"
Кажется что Вы можете реализовать нечто похожее. Если я правильно понял все объекты наследуются от какого-то базового. Можете ли вы для этого базового объекта добавить одно поле типа iValue, в которое из односкрипта можно установить любое значение? 
Например
```bsl
Реквизиты = Новый Структура("Поле1","");
. . .
ПолеВвода1 = Форма1.ЭлементыУправления.Добавить(Ф.ПолеВвода());
ПолеВвода1.Имя = "Поле1"
ПолеВвода1.НекийКонтейнер = Реквизиты; // я не смог придумать достойное наименование но это поле iValue, в которое я записал структуру

// И где-бы я не был я всегда могу по разным событиям манипулировать с реквизитами
// например вот так при изменении
. . .
ПолеВвода1.НекийКонтейнер[ПолеВвода1.Имя] = ПолеВвода1.Текст; 
```

**Comment by Nivanchenko** [comment]
Кажется я в синтаксисе структуры наврал, но суть примерно такая.

**Comment by Nivanchenko** [comment]
`Мне так и не понятна передача парамерта в обработчик события. Му ведь и так в скрипте находимся, весь контекст доступен.`
Передача параметров не так, что бы необходимая самоцель, но при использовании Действия, она появляется автоматически.

**Comment by ahyahy** [comment]
Я построил работу с библиотекой особым образом.
Формирую все файлы *.cs с помощью односкрипта.
Отправной точкой при их формировании служит справка. Это ведь каталог с html файлами, которые составляют справку на моём сайте. Скрипт анализирует их находит свойства, методы, перечисления, параметры и т.д.
По моему алгоритму *.cs перезаписываются. Поэтому для того чтобы исправить метод, мне нужно найти решение для одного случая. Объекты в библиотеке наследуются, повторяя структуру классов MSDN. Иногда в алгоритме исправляю только свойство родителя, иногда алгоритм однотипно меняет у объектов одноименные свойства. Если интересно, посмотрите файл 
...tests/ГенерацияCS.os в моём репозитории. Это и есть тот скрипт. Время занимает обдумывание задачи, исправление ошибок и тестирование, но не запись содержимого *.cs
Ф.АргументыСобытия.Параметр присутствует как аргумент у каждого события, вернее будет присутствовать. Он под капотом и принимает значения null, экземпляр ScriptEngine.HostedScript.Library.DelegateAction или экземпляр osf.ClDictionaryEntry
null - по умолчанию и как бы соответствует строковому типу свойства-события.
Можно и другие типы теоретически наприсваивать свойству-событию объекта, остановился пока на этих.

**Comment by Nivanchenko** [comment]
`Я построил работу с библиотекой особым образом.
Формирую все файлы *.cs с помощью односкрипта.`
Это гениально, я пребываю в шоке. Пойду попробую вникнуть. А справка как была написана? Только не говорите, что как-то тоже автоматически, магия же тогда какая-то =)

**Comment by ahyahy** [comment]
Библиотека написана для всех вас, программистов, админов, просто любителей программирования. Её можно сделать лучше, если использовать на практике, если обсуждать, предлагать, советовать... Так что, пока могу - помогу.
Как указано в справке, элементы управления наследуются от Компонент (Component).
Да, это возможно, добавить наследуемое поле или свойство. Подумаю, обсудим.

**Comment by ahyahy** [comment]
Вот на справку много времени ушло, почти два года. Просмотрел инет, сделал шаблон страницы примерно как у KiXforms.NET v3.01 Final, но близко к стилю справки 1С. Я ведь поначалу KiXforms хотел прикрутить к односкрипту. Но там много чего нет, календарей например. И так по шаблону, страница за страницей создавал справку в Notepad++, паралельно что то пробуя на C# и изучая его. Когда перевёл основные необходимые минимально свойства и методы вплотную занялся кодом.

**Comment by ahyahy** [comment]
> 
> 
> Мне кажется я Вас уже замучил, но у меня еще возникла идея. В 1Ске каждый элементы формы биндится к данным, т.е. у элемента есть реквизит Данные = "Объект.Наименование" Кажется что Вы можете реализовать нечто похожее. Если я правильно понял все объекты наследуются от какого-то базового. Можете ли вы для этого базового объекта добавить одно поле типа iValue, в которое из односкрипта можно установить любое значение? Например
> 
> ```bsl
> Реквизиты = Новый Структура("Поле1","");
> . . .
> ПолеВвода1 = Форма1.ЭлементыУправления.Добавить(Ф.ПолеВвода());
> ПолеВвода1.Имя = "Поле1"
> ПолеВвода1.НекийКонтейнер = Реквизиты; // я не смог придумать достойное наименование но это поле iValue, в которое я записал структуру
> 
> // И где-бы я не был я всегда могу по разным событиям манипулировать с реквизитами
> // например вот так при изменении
> . . .
> ПолеВвода1.НекийКонтейнер[ПолеВвода1.Имя] = ПолеВвода1.Текст; 
> 

У контролов есть свойство **ЭлементУправления.Метка (Control.Tag)**. По моему это то самое. Оно имеет тип значения **Коллекция (Collection)**, это тип из библиотеки. В нём можно сохранять объекты произвольного типа, и структуры тоже. Я набросал пример.

```bsl
ПодключитьВнешнююКомпоненту("C:\444\111\OneScriptForms\OneScriptForms\bin\Debug\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();

Реквизиты = Новый Структура("Поле1","ЧтоТоТам");

ПолеВвода1 = Форма1.ЭлементыУправления.Добавить(Ф.ПолеВвода());
ПолеВвода1.Имя = "Поле1";

Сообщить("ТипЗнч(ПолеВвода1.Метка) = " + ТипЗнч(ПолеВвода1.Метка));
ПолеВвода1.Метка.Добавить(Реквизиты, "Реквизиты");// установили значение в коллекции по индексу 0

НашаСтруктура = ПолеВвода1.Метка.Элемент(0);
Знач1 = НашаСтруктура["Поле1"];
Сообщить("Знач1 = " + Знач1);

НашаСтруктура["Поле1"] = "ДругоеЧтоТоТам";
Знач2 = НашаСтруктура["Поле1"];
Сообщить("Знач2 = " + Знач2);

Пока Ф.Продолжать Цикл
	Выполнить(Ф.ПолучитьСобытие());
КонецЦикла;
```

**Comment by Nivanchenko** [comment]
Да, кажется это то что надо. Спасибо. Отправлено с моего телефона Huawei-------- Исходное сообщение --------От: Vladimir Aleshechkin ***@***.***>Дата: вс, 17 окт. 2021 г., 14:30Кому: ahyahy/OneScriptForms ***@***.***>Копия: Nikita Ivanchenko ***@***.***>, Author ***@***.***>Тема: Re: [ahyahy/OneScriptForms] Предложение. Обработчики событий форм и элементов (#5)

Мне кажется я Вас уже замучил, но у меня еще возникла идея. В 1Ске каждый элементы формы биндится к данным, т.е. у элемента есть реквизит Данные = "Объект.Наименование" Кажется что Вы можете реализовать нечто похожее. Если я правильно понял все объекты наследуются от какого-то базового. Можете ли вы для этого базового объекта добавить одно поле типа iValue, в которое из односкрипта можно установить любое значение? Например
Реквизиты = Новый Структура("Поле1","");
. . .
ПолеВвода1 = Форма1.ЭлементыУправления.Добавить(Ф.ПолеВвода());
ПолеВвода1.Имя = "Поле1"
ПолеВвода1.НекийКонтейнер = Реквизиты; // я не смог придумать достойное наименование но это поле iValue, в которое я записал структуру

// И где-бы я не был я всегда могу по разным событиям манипулировать с реквизитами
// например вот так при изменении
. . .
ПолеВвода1.НекийКонтейнер[ПолеВвода1.Имя] = ПолеВвода1.Текст; 


У контролов есть свойство ЭлементУправления.Метка (Control.Tag). По моему это то самое. Оно имеет тип значения Коллекция (Collection), это тип из библиотеки. В нём можно сохранять объекты произвольного типа, и структуры тоже. Я набросал пример.
ПодключитьВнешнююКомпоненту("C:\444\111\OneScriptForms\OneScriptForms\bin\Debug\OneScriptForms.dll");
Ф = Новый ФормыДляОдноСкрипта();
Форма1 = Ф.Форма();
Форма1.Отображать = Истина;
Форма1.Показать();
Форма1.Активизировать();

Реквизиты = Новый Структура("Поле1","ЧтоТоТам");

ПолеВвода1 = Форма1.ЭлементыУправления.Добавить(Ф.ПолеВвода());
ПолеВвода1.Имя = "Поле1";

Сообщить("ТипЗнч(ПолеВвода1.Метка) = " + ТипЗнч(ПолеВвода1.Метка));
ПолеВвода1.Метка.Добавить(Реквизиты, "Реквизиты");// установили значение в коллекции по индексу 0

НашаСтруктура = ПолеВвода1.Метка.Элемент(0);
Знач1 = НашаСтруктура["Поле1"];
Сообщить("Знач1 = " + Знач1);

НашаСтруктура["Поле1"] = "ДругоеЧтоТоТам";
Знач2 = НашаСтруктура["Поле1"];
Сообщить("Знач2 = " + Знач2);

Пока Ф.Продолжать Цикл
	Выполнить(Ф.ПолучитьСобытие());
КонецЦикла;

**Comment by Nivanchenko** [comment]
Метка, то что нужно. А в релизе 1.1 в события можно устанавливать действие. Огромное спасибо 🙏👍
