### ISSUE TITLE
Двойной клик в сетке данных

### ISSUE THREAD

**Issue by ComradLinch** [ahyahy/OneScriptForms#6]
Добрый день. В объекте СеткаДанных в колонке СтильКолонкиПолеВвода не отрабатывает событие ДвойноеНажатие, видимо потому что при клике по полю ввода включает режим выделения текста, даже с включенным свойством ТолькоПросмотр. Было бы очень удобно, если бы для колонки/сетки можно было отключать этот режим, чтобы полноценно работать со всеми ячейками.

UPD Все таки ДвойноеНажатие отрабатывает, но нужно очень точно попасть между границей ячейки и полем ввода в ячейке, что не очень удобно.

**Comment by ahyahy** [comment]
Добрый вечер. СтильКолонкиПолеВвода не имеет события  DoubleClick. СтильКолонкиПолеВвода содержит ПолеВвода (TextBox), у которого есть событие DoubleClick, но до него сетка данных добраться не дает, она так устроена.
Описание я нашел здесь [Как поймать двойной щелчок в моей сетке данных](https://www-syncfusion-com.translate.goog/faq/windowsforms/datagrid?_x_tr_sl=auto&_x_tr_tl=ru&_x_tr_hl=ru&_x_tr_pto=nui)
Цитата:
_Проблема в том, что первый щелчок двойного щелчка может быть пойман сеткой данных (и использован для активации ячейки), 
в то время как второй щелчок переместится в текстовое поле для объекта стиля столбца. Это означает, что TextBox считает, 
что это однократный щелчок, и не запускает свое событие doubleclick. Одно из решений - отметить время щелчка, 
пойманного сеткой данных. Затем посмотрите на этот раз в обработчике mousedown TextBox, чтобы увидеть, действительно 
ли одиночный щелчок, на который смотрит TextBox, является частью двойного щелчка._
Но доработать можно. Я добавил в библиотеку для СтильКолонкиПолеВвода свойство - ДвойноеНажатие (Control.DoubleClick). В скрипте будет выглядеть так:

**СтильКолонкиПолеВвода1.ДвойноеНажатие = "СтильКолонкиПолеВвода1_ДвойноеНажатие()";**

Для тестирования используйте dll в каталоге test(**tests/OneScriptFormsDoubleClick.dll**)
Там же пример найдете (**tests/TestDoubleClick.os**).
Если всё получилось - перенесу в следующий релиз, он выйдет наверное в течение недели, но только, если поблема с DoubleClick решена.

**Comment by ahyahy** [comment]
В примере путь до библиотеки конечно подправьте.

**Comment by ComradLinch** [comment]
> Одно из решений - отметить время щелчка,
> пойманного сеткой данных. Затем посмотрите на этот раз в обработчике mousedown TextBox, чтобы увидеть, действительно
> ли одиночный щелчок, на который смотрит TextBox, является частью двойного щелчка.

К сожалению, этот способ не подходит, т.к. СтильКолонкиПолеВвода.ПолеВвода содержит объект ПолеВводаКолонки (DataGridTextBox), в котором отсутствуют какие либо обработчики...

Также попробовал OneScriptFormsDoubleClick.dll, при подключении компоненты вылетает ошибка:

`{Модуль D:\www\ce\src\gui_2_0.os / Ошибка в строке: 30 / Внешнее исключение (System.IO.FileLoadException): Не удалось загрузить файл или сборку "file:///D:\OScript\OneScriptForms1_1_0_0\OneScriptFormsDoubleClick.dll" либо одну из их зависимостей. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)}`

**Comment by ahyahy** [comment]
Это в моей справке для библиотеки такого обработчика нет. Я изменил библиотеку создав такое событие и вы его пока нигде не можете видеть. Измененный вариант я сохранил в OneScriptFormsDoubleClick.dll и к нему в пару сделал пример TestDoubleClick.os
Запустите например в командной строке, это должен быть надежный вариант запуска, как то так:
oscript.exe TestDoubleClick.os
Ещё можно на другой машине попробовать запустить, бывали случаи незапуска из-за системы. Проверьте ещё раз путь подключения библиотеки в TestDoubleClick.os
Тоесть не для gui_2_0.os этот вариант, он для TestDoubleClick.os, только для пробы.

**Comment by ComradLinch** [comment]
Попробовал на разных компах, запускал именно TestDoubleClick.os (путь к компоненте поправил на свой), ошибка повторяется
Вроде никаких отличий нет, кроме пути к файлам

```
D:\www\ce\src>oscript.exe testdoubleclick.os
{Модуль D:\www\ce\src\testdoubleclick.os / Ошибка в строке: 18 / Внешнее исключение (System.IO.FileLoadException): Не удалось загрузить файл или сборку "file:///D:\OScript\OneScriptForms1_1_0_0\OneScriptFormsDoubleClick.dll" либо одну из их зависимостей. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)}
```

**Comment by ahyahy** [comment]
Разобрался! Встречалось раньше такое, просто надо было память поднапрячь. Библиотека скачана из гитхаба, тоесть из интернета. Система этот файл ставит на блокировку. Нужно открыть свойства файла (OneScriptFormsDoubleClick.dll) и нажать кнопочку Разблокировать.

**Comment by ComradLinch** [comment]
Спасибо, помогло! Двойной клик отрабатывает 👍

**Comment by ahyahy** [comment]
Хорошо, добавляю в новый релиз.
